In [7]:
import pandas as pd

votacao = pd.read_csv('votacao_candidato.csv', encoding='latin-1', sep=';')

In [12]:
votacao_th = votacao.loc[votacao['Número candidato'] == 15123]
votacao_th.sort_values(by='Votos nominais', ascending=False)

,Cargo,Município,Nome candidato,Número candidato,Código município,Votos nominais,Data de carga
86305,Deputado Estadual,RIO DE JANEIRO,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,60011,13334,2025-09-07 03:30:58
29886,Deputado Estadual,SÃO JOÃO DE MERITI,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,59013,224,2025-09-07 03:30:58
86673,Deputado Estadual,DUQUE DE CAXIAS,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58335,207,2025-09-07 03:30:58
102221,Deputado Estadual,NOVA IGUAÇU,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58696,201,2025-09-07 03:30:58
32147,Deputado Estadual,CACHOEIRAS DE MACACU,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58157,185,2025-09-07 03:30:58
...,...,...,...,...,...,...,...
128862,Deputado Estadual,VARRE-SAI,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58084,0,2025-09-07 03:30:58
134361,Deputado Estadual,SÃO JOSÉ DE UBÁ,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58343,0,2025-09-07 03:30:58
139924,Deputado Estadual,CAMBUCI,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58173,0,2025-09-07 03:30:58
139317,Deputado Estadual,PORCIÚNCULA,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58815,0,2025-09-07 03:30:58
141459,Deputado Estadual,SÃO JOSÉ DO VALE DO RIO PRETO,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,59331,0,2025-09-07 03:30:58

In [13]:
votacao = pd.read_csv('votacao_candidato.csv', encoding='latin-1', sep=';')

In [16]:
votacao.sort_values(by='Votos nominais', ascending=False)

,Cargo,Município,Nome candidato,Número candidato,Código município,Zona,Votos nominais,Data de carga
80,Deputado Estadual,RIO DE JANEIRO,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,60011,218,3171,2025-09-07 03:30:58
142,Deputado Estadual,RIO DE JANEIRO,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,60011,10,1249,2025-09-07 03:30:58
20,Deputado Estadual,RIO DE JANEIRO,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,60011,23,1048,2025-09-07 03:30:58
112,Deputado Estadual,RIO DE JANEIRO,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,60011,24,687,2025-09-07 03:30:58
33,Deputado Estadual,RIO DE JANEIRO,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,60011,219,685,2025-09-07 03:30:58
...,...,...,...,...,...,...,...,...
157,Deputado Estadual,VARRE-SAI,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58084,43,0,2025-09-07 03:30:58
164,Deputado Estadual,NATIVIDADE,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58610,43,0,2025-09-07 03:30:58
159,Deputado Estadual,CARMO,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58238,102,0,2025-09-07 03:30:58
167,Deputado Estadual,CORDEIRO,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58297,52,0,2025-09-07 03:30:58
179,Deputado Estadual,PORCIÚNCULA,TIEGO RAIMUNDO DOS SANTOS SILVA,15123,58815,45,0,2025-09-07 03:30:58